# Generated by Django 3.1.3 on 2020-11-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20201112_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='logo',
            field=models.CharField(default='will smith.png', max_length=250),
            preserve_default=False,
        ),
    ]
